### ISSUE TITLE
0.2.0 release checklist

### ISSUE THREAD

**Issue by letmaik** [microsoft/scitt-ccf-ledger#80]
Checklist:
- [x] Link this issue to the correct milestone for this version.
- [x] Make sure all issues/PRs for the milestone are closed/merged.
- [x] Create a PR to update `CHANGELOG.md`.
  - [ ] If this release upgrades CCF to the next major version, add the following note in the changelog:
         "In order to upgrade an existing service to this version, it must first be upgraded to the version preceding this version."
- [x] Create a [release](https://github.com/microsoft/scitt-ccf-ledger/releases) with the new version number as git tag.
- [x] Check that CI is green.
- [x] Close the [milestone](https://github.com/microsoft/scitt-ccf-ledger/milestones) for this release.
- [x] Close this issue.
